#! /bin/bash
# Source: https://coderwall.com/p/mk18zq/automatic-git-version-tagging-for-npm-modules
echo "auto-tag check"
version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/package.json | grep '^\+.*version' | sed 's/[^0-9\.]//g'`
if [ "$version" != "" ]; then
  #git tag -a "v$version" -m "`git log -1 --format=%s`"
  git tag "v$version"
  echo "Created a new tag, v$version"
fi